apiVersion: v1
kind: Service
metadata:
  name: trainee-service
spec:
  type: LoadBalancer
  selector:
    app: trainee-deployment
  ports:
    - protocol: TCP
      port: 4203
      targetPort: 80
      nodePort: 30003
