apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  type: LoadBalancer
  selector:
    app: profile-deployment
  ports:
    - protocol: TCP
      port: 4202
      targetPort: 80
      nodePort: 30002
