apiVersion: v1
kind: Service
metadata:
  name: shell-service
spec:
  type: LoadBalancer
  selector:
    app: shell-deployment
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80 
